Add optional ability to configure dmarc RUA and RUF destinations
schubergphilis/terraform-aws-mcaf-ses pull request #7
Opened 2022-10-03 14:11 UTC by stimmerman

This will make it possible to configure a RUA or RUF email adres to send DMARC reports to.

2022-10-04 07:14 UTC, marwinbaumannsbp submitted a review, later dismissed

2022-10-04 10:02 UTC, shoekstra requested changes

2022-10-04 10:02 UTC, shoekstra commented on dmarc.tf
> +
```suggestion
```

It felt cumbersome to repeat the `rua=` in the variable value (`dmarc_rua = "rua=email@address.com"`), so I changed it around a bit:

```hcl
resource "aws_route53_record" "dmarc" {
  count    = var.dmarc != null ? 1 : 0
  provider = aws.route53

  name    = "_dmarc.${var.domain}"
  ttl     = 600
  type    = "TXT"
  zone_id = data.aws_route53_zone.default.zone_id

  records = [join(";", compact([
    var.dmarc.policy,
    var.dmarc != null ? var.dmarc.rua != null ? "rua=${var.dmarc.rua}" : null : null,
    var.dmarc != null ? var.dmarc.ruf != null ? "ruf=${var.dmarc.ruf}" : null : null,
  ]))]
}
```

Usage now looks something like this:

```
module "ses" {
  providers = { aws = aws, aws.route53 = aws }
  source    = "../.."
  domain    = "mydomain.com"
  tags      = {}

  dmarc = {
    rua = "mailto:email@address.com"
  }
}

```

2022-10-05 07:20 UTC, shoekstra approved these changes

2022-10-05 07:21 UTC, merged